[package]
name = "normal-data"
version = "0.1.0"
edition = "2021"

[dependencies]
mint = { version = "0.5.9", features = ["serde"] }
serde = {version = "1.0.197", features = ["derive"]}
serde_json = "1.0.115"
