//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub data_transaction_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub ecg1: i32,
    pub ecg2: i32,
    pub quaternion: Json,
    pub accel: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::data_transaction::Entity",
        from = "Column::DataTransactionId",
        to = "super::data_transaction::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DataTransaction,
}

impl Related<super::data_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DataTransaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
